const TOGGLE_VISIBLE_JOB = 'TOGGLE_VISIBLE_JOB'
const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM'
const SET_DETAIL_JOB = 'SET_DETAIL_JOB'
const INITIALIZE_DETAIL_STATE = 'INITIALIZE_DETAIL_STATE'
const EDIT_DETAIL_STATE = 'EDIT_DETAIL_STATE'
const INCREMENT_ACTIVE_STEP = 'INCREMENT_ACTIVE_STEP'
const DECREMENT_ACTIVE_STEP = 'DECREMENT_ACTIVE_STEP'
const CHANGE_ACTIVE_STEP = 'CHANGE_ACTIVE_STEP'
export default {
  TOGGLE_VISIBLE_JOB,
  UPDATE_SEARCH_TERM,
  SET_DETAIL_JOB,
  INITIALIZE_DETAIL_STATE,
  EDIT_DETAIL_STATE,
  INCREMENT_ACTIVE_STEP,
  DECREMENT_ACTIVE_STEP,
  CHANGE_ACTIVE_STEP
}
