export default {
  UPDATE_FIELD: 'UPDATE_FIELD',
  AUTHENTICATION_SUCCESS: 'AUTHENTICATION_SUCCESS',
  AUTHENTICATION_FAILURE: 'AUTHENTICATION_FAILURE',
  AUTHENTICATION_ATTEMPT: 'AUTHENTICATION_ATTEMPT',
}
